### ISSUE TITLE
Trained model?

### ISSUE THREAD

**Issue by andreped** [jpdefrutos/DDMR#11]
It would be great to make one of the pretrained models available, as it would enable others to easily finetune on their own data, to 1) reproduce our experiments more easily and 2) make the tool more plug-and-play.

I would make the neuro model available as that should be the most flexible one, as it trained on a much larger dataset with a lot more classes.

**Comment by jpdefrutos** [comment]
Trained model were made available in the latest release: https://github.com/jpdefrutos/DDMR/releases/tag/trained_models_v1
