### ISSUE TITLE
Add acknowledgements

### ISSUE THREAD

**Issue by andreped** [jpdefrutos/DDMR#14]
We should acknowledge `Voxelmorph` in its own Acknowledgements section in the README, as our repository is built upon this project.

You could choose either to add their bibtex:
https://github.com/andreped/H2G-Net#acknowledgements

or add acknowledgements in words (with hyperlinks):
https://github.com/andreped/super-ml-pets#acknowledgements

**Comment by jpdefrutos** [comment]
see commit [91b1738](https://github.com/jpdefrutos/DDMR/commit/91b17385d464b34544045107dcc0348bffa64ef0)
